"pkg:more":
  - '### Nuget Package\s*Json\.More\.Net'

"pkg:schema":
  - '### Nuget Package\s*JsonSchema\.Net[^.]'

"pkg:schema-generation":
  - '### Nuget Package\s*JsonSchema\.Net\.Generation'

"pkg:schema-datagen":
  - '### Nuget Package\s*JsonSchema\.Net\.DataGeneration'

"pkg:schema-data":
  - '### Nuget Package\s*JsonSchema\.Net\.Data'

"pkg:schema-openapi":
  - '### Nuget Package\s*JsonSchema\.Net\.OpenApi'

"pkg:schema-unique-keys":
  - '### Nuget Package\s*JsonSchema\.Net\.UniqueKeys'

"pkg:logic":
  - '### Nuget Package\s*JsonLogic'

"pkg:pointer":
  - '### Nuget Package\s*JsonPointer\.Net'

"pkg:path":
  - '### Nuget Package\s*JsonPath\.Net'

"pkg:patch":
  - '### Nuget Package\s*JsonPatch\.Net'

"pkg:yaml":
  - '### Nuget Package\s*Yaml2JsonNode'
