"pkg:more":
  - Json.More/**/*

"pkg:schema":
  - JsonSchema/**/*

"pkg:schema-generation":
  - JsonSchema.Generation/**/*

"pkg:schema-data":
  - JsonSchema.Data/**/*

"pkg:pointer":
  - JsonPointer/**/*

"pkg:path":
  - JsonPath/**/*

"pkg:patch":
  - JsonPatch/**/*

"documentation":
  - docs_source/**/*

"build pipeline":
  - .github/workflows/**/*