"pkg:more":
  - Json.More/**/*

"pkg:schema":
  - JsonSchema/**/*

"pkg:schema-generation":
  - JsonPatch/**/*

"pkg:pointer":
  - JsonPointer/**/*

"pkg:path":
  - JsonPath/**/*

"pkg:patch":
  - JsonPatch/**/*
