"pkg:more":
  - src/Json.More/**/*

"pkg:schema":
  - src/JsonSchema/**/*

"pkg:schema-generation":
  - src/JsonSchema.Generation/**/*

"pkg:schema-generation-dataannotations":
  - src/JsonSchema.Generation.DataAnnotations/**/*

"pkg:schema-datagen":
  - src/JsonSchema.DataGeneration/**/*

"pkg:schema-codegen":
  - src/JsonSchema.CodeGeneration/**/*

"pkg:schema-data":
  - src/JsonSchema.Data/**/*

"pkg:schema-openapi":
  - src/JsonSchema.OpenApi/**/*

"pkg:schema-unique-keys":
  - src/JsonSchema.UniqueKeys/**/*

"pkg:schema-array-ext":
  - src/JsonSchema.ArrayExt/**/*

"pkg:logic":
  - src/JsonLogic/**/*

"pkg:pointer":
  - src/JsonPointer/**/*

"pkg:path":
  - src/JsonPath/**/*

"pkg:patch":
  - src/JsonPatch/**/*

"pkg:json-e":
  - src/JsonE/**/*

"pkg:yaml":
  - src/Yaml2JsonNode/**/*

"build pipeline":
  - .github/workflows/**/*

"json-everything.net":
  - any: ['json-everything.net/**/*']
