"pkg:more":
  - Json.More/**/*

"pkg:schema":
  - JsonSchema/**/*

"pkg:schema-generation":
  - JsonSchema.Generation/**/*

"pkg:schema-datagen":
  - JsonSchema.DataGeneration/**/*

"pkg:schema-codegen":
  - JsonSchema.CodeGeneration/**/*

"pkg:schema-data":
  - JsonSchema.Data/**/*

"pkg:schema-openapi":
  - JsonSchema.OpenApi/**/*

"pkg:schema-unique-keys":
  - JsonSchema.UniqueKeys/**/*

"pkg:logic":
  - JsonLogic/**/*

"pkg:pointer":
  - JsonPointer/**/*

"pkg:path":
  - JsonPath/**/*

"pkg:patch":
  - JsonPatch/**/*

"pkg:json-e":
  - JsonE/**/*

"pkg:yaml":
  - Yaml2JsonNode/**/*

"build pipeline":
  - .github/workflows/**/*

"json-everything.net":
  - any: ['json-everything.net/**/*']
