pool:
  vmImage: windows-2019

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'json-everything.sln'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3'
  inputs:
    packageType: 'sdk'
    useGlobalJson: false

- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(coreSolution)'
    msbuildArgs: '/t:Restore'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: Build Core Solution
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Pack'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*Test*/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: VSBuild@1
  displayName: Pack Core Solution
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Pack'

- task: CopyFiles@2
  displayName: Copy Packages to Artifact Directory
  inputs:
    Contents: 'packages\*.nupkg'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: Packages