name: Bug Report
description: A library isn't doing what you expect it should
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help make this project better!
  - type: dropdown
    id: package
    attributes:
      label: Nuget Package
      description: What package are you using?
      options:
        - Json.More.Net
        - JsonLogic
        - JsonPath.Net
        - JsonPatch.Net
        - JsonPointer.Net
        - JsonSchema.Net
        - JsonSchema.Net (language pack)
        - JsonSchema.Net.Data
        - JsonSchema.Net.DataGeneration
        - JsonSchema.Net.CodeGeneration
        - JsonSchema.Net.Generation
        - JsonSchema.Net.OpenApi
        - JsonSchema.Net.UniqueKeys
        - Yaml2JsonNode
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Mac
        - Linux
    validations:
      required: false
  - type: dropdown
    id: target
    attributes:
      label: .Net Target (if relevant, please specify the version in the description)
      options:
        - .Net Framework
        - .Net Core (3.1 or before)
        - .Net (5 or after)
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Please add test code or steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Is there any other information you'd like to share regarding this bug?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gregsdennis/json-everything/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
