name: Analyze JsonPath.Net

on:
  pull_request:
    paths-ignore:
      - 'docs/**/*'
      - 'docs_source/**/*'

jobs:
  publish:
    needs: build
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

        # Set up
      - name: Create local manifest file
        if: github.event_name == 'pull_request'
        run: dotnet new tool-manifest
      - name: Install analyzer
        if: github.event_name == 'pull_request'
        run: dotnet tool install SemVerAnalyzer

      - name: Analyze path
        id: analyze-path
        if: github.event_name == 'pull_request'
        # multiline comment support details: https://github.community/t/set-output-truncates-multiline-strings/16852/3
        run: |
          dotnet analyze-semver -a JsonPath/bin/Release/netstandard2.1/JsonPath.Net.dll -o semver-report-path.md -c build/semver_config.json
          unset HAS_REPORT
          unset REPORT
          if [ -s semver-report-path.md ]
          then
            HAS_REPORT='true'
            REPORT=$(<semver-report-path.md)
            REPORT="${REPORT//'%'/'%25'}"
            REPORT="${REPORT//$'\n'/'%0A'}"
            REPORT="${REPORT//$'\r'/'%0D'}"
            echo "::set-output name=REPORT::${REPORT}"
          fi
          echo ::set-output name=HAS_REPORT::${HAS_REPORT}

        # Report
      - if: steps.analyze-path.outputs.HAS_REPORT
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ${{ steps.analyze-path.outputs.REPORT }}
