name: .NET Core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**/*'
  pull_request:
    paths-ignore:
      - 'docs/**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: restore submodules
      run: git submodule update --init
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Create local manifest file
      run: dotnet new tool-manifest
    - name: Install analyzer
      run: dotnet tool install SemVerAnalyzer
    - name: Analyze more
      id: analyzemore
      run: |
        dotnet analyze-semver -a Json.More/bin/Release/netstandard2.0/Json.More.dll -o semver-report-more.md -c build/semver_config.json -p Json.More.Net
        unset HAS_REPORT
        if [-s semver-report-more.md]; then HAS_REPORT='true'
        echo ::set-output name=HAS_REPORT::${HAS_REPORT}
    - name: Analyze patch
      run: dotnet analyze-semver -a JsonPatch/bin/Release/netstandard2.0/JsonPatch.dll -o semver-report-patch.md -c build/semver_config.json -p JsonPatch.Net
    - name: Analyze path
      run: dotnet analyze-semver -a JsonPath/bin/Release/netstandard2.1/JsonPath.Net.dll -o semver-report-path.md -c build/semver_config.json
    - name: Analyze pointer
      run: dotnet analyze-semver -a JsonPointer/bin/Release/netstandard2.0/JsonPointer.Net.dll -o semver-report-pointer.md -c build/semver_config.json
    - name: Analyze schema
      id: analyzeschema
      run: |
        dotnet analyze-semver -a JsonSchema/bin/Release/netstandard2.0/JsonSchema.Net.dll -c build/semver_config.json
        unset HAS_REPORT
        if [-s semver-report-schema.md]; then HAS_REPORT='true'
        echo ::set-output name=HAS_REPORT::${HAS_REPORT}
    - uses: harupy/comment-on-pr@master
        if: ${{ steps.analyzemore.outputs.HAS_REPORT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: semver-report-more.md
    # - uses: harupy/comment-on-pr@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       filename: semver-report-patch.md
    # - uses: harupy/comment-on-pr@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       filename: semver-report-path.md
    # - uses: harupy/comment-on-pr@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       filename: semver-report-pointer.md
    - uses: harupy/comment-on-pr@master
        if: ${{ steps.analyzeschema.outputs.HAS_REPORT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: semver-report-schema.md
