# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonE.Net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-e.yml
      - src/JsonE/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      # Publish
      - name: publish json-e
        id: publish_e
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/JsonE/JsonE.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: json-e-v*
          PACKAGE_NAME: JsonE.Net
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
          if-no-files-found: error
