# https://github.com/marketplace/actions/publish-nuget
name: Publish Json.More.Net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-more.yml
      - src/Json.More/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      # Publish
      - name: publish more
        id: publish_more
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Json.More/Json.More.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: more-v*
          PACKAGE_NAME: Json.More.Net
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
