name: Publish json-everything.net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - src/Json.More/**
      - src/JsonLogic/**
      - src/JsonPatch/**
      - src/JsonPath/**
      - src/JsonPointer/**
      - src/JsonSchema/**
      - src/JsonSchema.Data/**
      - src/JsonSchema.UniqueKeys/**
      - src/JsonSchema.Generation/**
      - src/JsonSchema.DataGeneration/**
      - src/JsonSchema.CodeGeneration/**
      - json-everything.net/**
      - .github/workflows/publish-site.yml
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore submodules
        run: git submodule update --init
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Pre-build solution
        run: dotnet build json-everything.sln -c Release --no-restore
      # - name: Get sponsor data
      #   run: |
      #     cd tools/GenerateSponsorList/bin/Release/net8.0
      #     dotnet GenerateSponsorList.dll
      #     cp sponsor-data.json ../../../../../json-everything.net/wwwroot/data/
      #   env:
      #     GenerateSponsorList: ${{ secrets.GENERATE_SPONSOR_LIST }}
      - name: Build
        run: dotnet publish json-everything.net/json-everything.net.csproj -c Release --no-restore -o bin
      - name: Add .nojekyll file
        run: touch bin/wwwroot/.nojekyll
      - name: Copy index.html files
        run: |
          mkdir bin/wwwroot/json-schema/ && cp bin/wwwroot/index.html bin/wwwroot/json-schema/
          mkdir bin/wwwroot/json-path/ && cp bin/wwwroot/index.html bin/wwwroot/json-path/
          mkdir bin/wwwroot/json-patch/ && cp bin/wwwroot/index.html bin/wwwroot/json-patch/
          mkdir bin/wwwroot/json-pointer/ && cp bin/wwwroot/index.html bin/wwwroot/json-pointer/
          mkdir bin/wwwroot/json-logic/ && cp bin/wwwroot/index.html bin/wwwroot/json-logic/
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: bin/wwwroot
