# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net.DataGeneration
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-schema-datagen.yml
      - src/JsonSchema.DataGeneration/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      # Publish
      - name: publish schema data generation
        id: publish_schema_datageneration
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: schema-datageneration-v*
          PACKAGE_NAME: JsonSchema.Net.DataGeneration
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
          if-no-files-found: error
