# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-schema.yml
      - src/JsonSchema/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build src/JsonSchema/JsonSchema.csproj -c Release --no-restore
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            src/JsonSchema/bin/**/*
            src/JsonSchema/obj/**/*
  publish:
    needs: build
    name: pack & publish localizations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [ base, de, es, it, ko, nb-NO, pl-PL, ru, sv-SE, tr-TR ]
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: src/JsonSchema/bin
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: pack & push
        run: |
          cd src/JsonSchema
          dotnet pack -o nupkg/ -c Release -p:ResourceLanguage=${{ matrix.lang }} --no-build
          dotnet nuget push nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      # - name: archive package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: archive-package-${{ matrix.lang }}
      #     path: |
      #       **/*.nupkg
      #       **/*.snupkg
