# https://github.com/marketplace/actions/publish-nuget
name: Publish Yaml2JsonNode
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - Yaml2JsonNode/**
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      # Publish
      - name: publish yaml
        id: publish_yaml
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Yaml2JsonNode/Yaml2JsonNode.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: yaml-v*
          PACKAGE_NAME: Yaml2JsonNode
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
          if-no-files-found: error
