# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net.ArrayExt
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-schema-array-ext.yml
      - src/JsonSchema.ArrayExt/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      # Publish
      - name: publish schema array ext
        id: publish_schema_array_ext
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/JsonSchema.ArrayExt/JsonSchema.ArrayExt.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: schema-array-ext-v*
          PACKAGE_NAME: JsonSchema.Net.ArrayExt
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
