# https://github.com/marketplace/actions/deploy-to-heroku
name: Publish json-everything.net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - Json.More/**
      - JsonLogic/**
      - JsonPatch/**
      - JsonPath/**
      - JsonPointer/**
      - JsonSchema/**
      - JsonSchema.Data/**
      - JsonSchema.UniqueKeys/**
      - JsonSchema.Generation/**
      - JsonSchema.DataGeneration/**
      - json-everything.net/**
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: restore submodules
        run: git submodule update --init
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish json-everything.net/json-everything.net.csproj -c Release --no-restore -o bin
      # - name: Publish
      #   run: rm -rf docs && cp -a bin/wwwroot/. docs/
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: bin/wwwroot
      # - name: Commit changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add --all
      #     git commit -m "rebuilt documentation"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
