# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-schema.yml
      - src/JsonSchema/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    # needs: build
    name: build, pack, (maybe sign?), and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [ base, de, es, it, ko, nb-NO, pl-PL, ru, sv-SE, tr-TR ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      # Ideally I'd like to build once, but the pack doesn't seem to work
      # without having the full source and build artifacts available, and
      # it doesn't take long anyway.
      - name: Build
        run: dotnet build src/JsonSchema/JsonSchema.csproj -c Release --no-restore
      - name: Pack
        run: |
          cd src/JsonSchema
          dotnet pack -o nupkg/ -c Release -p:ResourceLanguage=${{ matrix.lang }} --no-build
      # TODO: sign package before push
      - name: Push
        run: |
          cd src/JsonSchema
          dotnet nuget push nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      # - name: archive package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: archive-package-${{ matrix.lang }}
      #     path: |
      #       **/*.nupkg
      #       **/*.snupkg
