# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net.Generation.DataAnnotations
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - .github/workflows/publish-schema-gen-annotations.yml
      - src/JsonSchema.Generation.DataAnnotations/**
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      # Publish
      - name: publish schema generation dataannotations
        id: publish_schema_generation_dataannotations
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/JsonSchema.Generation.DataAnnotations/JsonSchema.Generation.DataAnnotations.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: schema-gen-v*
          PACKAGE_NAME: JsonSchema.Net.Generation.DataAnnotations
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
